//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "file")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub original_name: String,
    pub path: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_one = "super::private_message::Entity")]
    PrivateMessage,
}

impl Related<super::private_message::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PrivateMessage.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
