//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "public_room")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    #[sea_orm(unique)]
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::public_message::Entity")]
    PublicMessage,
}

impl Related<super::public_message::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PublicMessage.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
